import = [
   "~/.dotfiles/alacritty/colors.toml",
   "~/.dotfiles/alacritty/fonts.toml",
  ]

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
padding = { x= 5, y= 5 }
dynamic_padding = true

[cursor]
style =  { shape = "Block", blinking= "On" }
unfocused_hollow = true

