theme="tokyonight"

[editor]
mouse=true
cursorline=true
completion-replace = true
color-modes=true
bufferline="multiple"
line-number = "relative"
end-of-line-diagnostics = "hint"

[editor.statusline]
center = ["version-control"]
[editor.cursor-shape]
insert="bar"
normal="block"
select="underline"

[editor.indent-guides]
render=true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.file-picker]
hidden = false

[editor.lsp]
snippets = true

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·"

[editor.inline-diagnostics]
cursor-line = "error"

[keys.normal]
G = "goto_file_end"
X = "extend_line_above"
ret = ["move_line_down", "goto_line_start"]
esc = ["collapse_selection", "keep_primary_selection"]
C-s = ":w!"
C-w = ":buffer-close"
y = [":clipboard-yank", "yank"]
C-v = [":clipboard-paste-before"]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]

[keys.insert]
C-s = [":w!", "normal_mode"]
C-w = [":buffer-close", "normal_mode"]
C-v = [":clipboard-paste-before"]

[keys.select]
y = [":clipboard-yank", "yank"]

[keys.insert.j]
k = "normal_mode"
